version: "2"
services:
    web:
        image: elixir:1.12.3
        build: .
        ports:
            - "4000:4000"
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_HOST=${POSTGRES_HOST}
        volumes:
            - ./:/app
        depends_on:
            - db
    db:
        image: postgres:13
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
