version: "2"
services:
    web:
        container_name: logbook-web
        image: elixir:1.12.3
        build: .
        ports:
            - "4000:4000"
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_HOST=${POSTGRES_HOST}
        volumes:
            - ./:/app
        depends_on:
            - db
    db:
        container_name: logbook-postgres-db
        restart: always
        image: postgres:13
        volumes:
            - ./.database:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
