name: build and test

on:
    push:
        branches:
            - ian/docker

jobs:
  build:

    name: build and test
    runs:
        - using: 'docker'
        - image: 'Dockerfile'

    steps:
    - uses: actions/checkout@v2

    - name: notify slack that build has initiated
      if: ${{ github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/prod' }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: '#0000FF'
        SLACK_TITLE: ':checkered_flag: Build INITIATED'
        SLACK_FOOTER: 'git@github.com:iccowan/logbook.git'

    - name: setup postgresql
      # You may pin to the exact commit or the version.
      # uses: Harmon758/postgresql-action@0be19fa37850b22cb4c9bbf28a03abbf44abd863
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        # POSTGRES_DB - name for the default database that is created
        postgresql db: logbook_dev
        # POSTGRES_USER - create the specified user with superuser power
        postgresql user: postgres
        # POSTGRES_PASSWORD - superuser password
        postgresql password: postgres

    - name: load/save cache
      uses: actions/cache@v2.1.6
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: |
            deps
            _build
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: |
            ${{ runner.os }}-mix-

    - name: set up elixir
      uses: erlef/setup-elixir@885971a72ed1f9240973bd92ab57af8c1aa68f24
      with:
        elixir-version: '1.12.3' # Define the elixir version [required]
        otp-version: '22.3' # Define the OTP version [required]

    - name: set up hex (mix local.hex --force)
      run: docker-compose run web mix local.hex --force

    - name: set up rebar (mix local.rebar --force)
      run: docker-compose run web mix local.rebar --force

    - name: get dependencies (mix deps.get)
      run: docker-compose run web mix deps.get

    - name: audit dependencies (mix deps.audit)
      run: docker-compose run web mix deps.audit

    - name: sobelow security check (mix sobelow --verbose --exit)
      run: docker-compose run web mix sobelow --verbose --exit

    - name: credo code analysis (mix credo --all)
      run: docker-compose run web mix credo --all --verbose

    - name: dialyzer code analysis (mix dialyzer)
      run: docker-compose run web mix dialyzer

    - name: run tests (mix test)
      run: docker-compose run web mix test

    - name: notify slack on success
      if: ${{ success() && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/prod') }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: ${{ job.status }}
        SLACK_TITLE: ':white_check_mark: Build PASSING'
        SLACK_FOOTER: 'git@github.com:iccowan/logbook.git'

    - name: notify slack on fail
      if: ${{ failure() && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/prod') }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: ${{ job.status }}
        SLACK_TITLE: ':x: Build FAILING'
        SLACK_FOOTER: 'git@github.com:iccowan/logbook.git'
